DAS-1588 - Add HOSS regression test for collection with bounds variables
nasa/harmony-regression-tests pull request #38
Opened 2022-09-28 23:03 UTC by owenlittlejohns

## Description

This PR adds a regression test for HOSS to test changes for DAS-1588. The test makes a spatial (bounding box) and temporal subset request for a collection with bounds variables associated with the dimension variables.

The test uses `xarray` to compare output to a reference image, as first introduced to this notebook by @flamingbear.

## Jira Issue ID

DAS-1588

## Local Test Steps

* Pull this branch locally.
* Pull the DAS-1588-bounds branch of the HOSS repository (or master if the PR has been merged)
* Build the HOSS service image from the HOSS repository.
* Restart the Harmony services running in you local Harmony instance.
* Point the `harmony_host_url` to `http://localhost:3000` near the beginning of the notebook.
* Execute the notebook, paying particular attention to all Variable Subsetter and HOSS regression tests. These tests should all pass.

## PR Acceptance Checklist
* [x] Acceptance criteria met
* [x] Tests added/updated (if needed) and passing
* [x] Documentation updated (if needed)

2022-09-29 22:01 UTC, flamingbear requested changes
I have a question about how you compared the datasets.

2022-09-29 22:11 UTC, owenlittlejohns commented on test/sds/SDS_Regression.ipynb
> +    "    for variable_name, variable in output_data.variables.items():\n",
As discussed on Slack - I was missing that you could do `xarray.Dataset.equal` to compare all the variables in one go. Super nice.

2022-09-29 22:19 UTC, flamingbear approved these changes
Looks good. thanks.

2022-10-05 12:36 UTC, chris-durbin approved these changes

2022-10-05 13:49 UTC, merged